const { initDataFolder } = require('./utils');
fs = require('fs');
const noop = () => {};


initDataFolder()

/* 
for tables:
	get primary index
	create data table
	for indexes:
		create index tables
 */

console.log('Sorting', data.length, 'rows')
data.sort(function(x, y) {
	if (x[0] < y[0]) {
	  return -1;
	}
	if (x[0] > y[0]) {
	  return 1;
	}
	return 0;
});

console.log('writing', parseInt(data.length/1000), 'files')
var indexFileContent = 'index # example data generated by SkyLookup\n'
var linesInFile = 0
var contentToWrite = 'final #\n'
var nextFileName = 0
var firstLineInFile = ''

for (let i = 0; i < data.length; i++) {
	if (linesInFile < 1000) {
		contentToWrite += data[i][0] + ' ' + data[i][1] + '\n'
		if (linesInFile == 0) {
			firstLineInFile = data[i][0]
		}
		linesInFile += 1
	} else {
		fs.writeFileSync(dir + '/data/' + nextFileName + '.txt', contentToWrite, noop)
		linesInFile = 0
		contentToWrite = 'final #\n'
		indexFileContent += firstLineInFile + ' data/' + nextFileName + '.txt\n'
		firstLineInFile = ''
		nextFileName += 1
	}
}
// WRITE indexFileContent
console.log('writing index file')
fs.writeFileSync(dir + '/data/index.txt', indexFileContent, noop)




// fs.writeFile('', data, [encoding], [callback])